name: install-deps
description: Install dependencies

inputs:
  pkg-manager:
    required: true
  working-dir:
    required: false
    default: "."
   
runs:
  using: "composite"
  steps:
   - name: Install dependencies (npm)
     working-directory: ${{ inputs.working-dir }}
     if: ${{ inputs.pkg-manager == 'npm' }}
     run: npm ci
     shell: bash
   
   - name: Install dependencies (yarn)
     working-directory: ${{ inputs.working-dir }}
     if: ${{ inputs.pkg-manager == 'yarn' }}
     run: yarn install
     shell: bash

   - name: Install dependencies (pnpm)
     working-directory: ${{ inputs.working-dir }}
     if: ${{ inputs.pkg-manager == 'pnpm' }}
     run: pnpm install
     shell: bash

   - name: Verify that the node_modules exist
     working-directory: ${{ inputs.working-dir }}
     run: ls node_modules
     shell: bash