name: Test JS Actions

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  test-setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: ./js/actions/setup
        with:
          node-version: "22"

      - name: Install dependencies
        uses: ./js/actions/install-deps
        with:
          pkg-manager: "npm"

      - name: Run tests
        uses: ./js/actions/test
        with:
          pkg-manager: "npm"
          working-dir: "."
        